//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCMatch
    {
        public int Id { get; set; }
        public Nullable<int> SerieId { get; set; }
        public string Opponent { get; set; }
        public System.DateTime MatchDate { get; set; }
    }
}
